; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define ROOT "C:\Users\xiaoxin\Desktop\github\open-falcon-agent-windows"
#define MyAppName "agent"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "open-falcon"
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "agent.exe" 

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D9DE078A-AD88-4652-B3CF-1F4E4D729A37}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
VersionInfoVersion= {#MyAppVersion}
Uninstallable=yes
UninstallDisplayName={#MyAppName} {#MyAppVersion}
DisableProgramGroupPage=yes
InfoBeforeFile={#ROOT}\pack\install.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=agent-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin



[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
//Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
Source: "{#ROOT}\dist\agent.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ROOT}\dist\config.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Run]
Filename: "{app}\{#MyAppExeName}";Parameters: " --startup auto install";Description: "安装服务"; Flags: postinstall skipifsilent hidewizard runhidden
Filename: "{app}\{#MyAppExeName}";Parameters: " start";Description: "启动服务"; Flags:  postinstall skipifsilent hidewizard runhidden

[UninstallRun]
Filename: "{app}\{#MyAppExeName}";Parameters: " stop"    ;Flags: hidewizard runhidden
Filename: "{app}\{#MyAppExeName}";Parameters: " remove"  ;Flags: hidewizard runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[code]

function InitializeSetup(): boolean;
var
ResultStr: String;
ResultCode: Integer;
begin
if RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{D9DE078A-AD88-4652-B3CF-1F4E4D729A37}_is1', 'UninstallString', ResultStr) then
begin
ResultStr := RemoveQuotes(ResultStr);
Exec(ResultStr, '/silent', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;
result := true;
end;